"""Profile model template_username column

Revision ID: 90056772b91b
Revises: a56d95afb99d
Create Date: 2025-01-30 13:07:31.790819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90056772b91b'
down_revision: Union[str, None] = 'a56d95afb99d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('template_username', sa.String(), nullable=False))
    op.create_index(op.f('ix_profile_template_username'), 'profile', ['template_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_template_username'), table_name='profile')
    op.drop_column('profile', 'template_username')
    # ### end Alembic commands ###
