"""Profile steam link column

Revision ID: c3184b9cb053
Revises: 1ba74e7650ce
Create Date: 2025-02-02 01:03:01.195111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3184b9cb053'
down_revision: Union[str, None] = '1ba74e7650ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('steam_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'steam_link')
    # ### end Alembic commands ###
