"""Profile model slug column

Revision ID: fdcee33aff7d
Revises: 90056772b91b
Create Date: 2025-01-30 18:37:07.210400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdcee33aff7d'
down_revision: Union[str, None] = '90056772b91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('slug', sa.String(), nullable=False))
    op.create_index(op.f('ix_profile_slug'), 'profile', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_slug'), table_name='profile')
    op.drop_column('profile', 'slug')
    # ### end Alembic commands ###
