"""Profile steam is_steam_authenticated column

Revision ID: 496659b6047f
Revises: c3184b9cb053
Create Date: 2025-02-02 01:06:49.713975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '496659b6047f'
down_revision: Union[str, None] = 'c3184b9cb053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('is_steam_authenticated', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_profile_is_steam_authenticated'), 'profile', ['is_steam_authenticated'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_is_steam_authenticated'), table_name='profile')
    op.drop_column('profile', 'is_steam_authenticated')
    # ### end Alembic commands ###
