"""Profile model some columns

Revision ID: a56d95afb99d
Revises: 09580176e3ac
Create Date: 2025-01-30 12:52:40.291782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56d95afb99d'
down_revision: Union[str, None] = '09580176e3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('profile', sa.Column('avatar_frame_url', sa.String(), nullable=True))
    op.add_column('profile', sa.Column('description', sa.String(), nullable=True))
    op.add_column('profile', sa.Column('location', sa.String(), nullable=True))
    op.add_column('profile', sa.Column('location_flag_url', sa.String(), nullable=True))
    op.add_column('profile', sa.Column('player_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'player_level')
    op.drop_column('profile', 'location_flag_url')
    op.drop_column('profile', 'location')
    op.drop_column('profile', 'description')
    op.drop_column('profile', 'avatar_frame_url')
    op.drop_column('profile', 'avatar_url')
    # ### end Alembic commands ###
