"""Profile model

Revision ID: 09580176e3ac
Revises:
Create Date: 2025-01-29 15:47:45.305227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "09580176e3ac"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("steam_id", sa.String(), nullable=True),
        sa.Column(
            "link_type",
            postgresql.ENUM("with_username", "with_steam_id", name="profile_link_type"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profile_is_active"), "profile", ["is_active"], unique=False)
    op.create_index(op.f("ix_profile_link_type"), "profile", ["link_type"], unique=False)
    op.create_index(op.f("ix_profile_steam_id"), "profile", ["steam_id"], unique=False)
    op.create_index(op.f("ix_profile_username"), "profile", ["username"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_profile_username"), table_name="profile")
    op.drop_index(op.f("ix_profile_steam_id"), table_name="profile")
    op.drop_index(op.f("ix_profile_link_type"), table_name="profile")
    op.drop_index(op.f("ix_profile_is_active"), table_name="profile")
    op.drop_table("profile")
    op.execute("DROP TYPE profile_link_type;")
    # ### end Alembic commands ###
