services:
  postgresql:
    image: "postgres:latest"
    restart: always
    container_name: "steam_profile_postgresql"
    volumes:
      - steam_profile_postgresql_data:/var/lib/postgresql/data
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}

  app:
    build:
      context: .
    container_name: "steam_profile_app"
    depends_on:
      - postgresql
    ports:
      - "8000:${APP_PORT}"
    volumes:
      - .:/steam_profile_app/api
      - ./static:/steam_profile_app/api/static
      - ./templates:/steam_profile_app/api/templates
    env_file:
      - .env.dev
    environment:
      MODE: "DEV"

  pg-admin:
    image: dpage/pgadmin4
    container_name: steam_profile_admin
    restart: always
    depends_on:
      - postgresql
    ports:
      - "82:80"
    volumes:
      - steam_profile_pg_admin_data:/var/lib/pgadmin
    env_file:
      - .env.dev
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PG_ADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PG_ADMIN_PASSWORD}"

volumes:
  steam_profile_postgresql_data:
  steam_profile_pg_admin_data: