services:
  postgresql:
    image: "postgres:latest"
    restart: always
    container_name: "steam_profile_postgresql"
    volumes:
      - steam_profile_postgresql_data:/var/lib/postgresql/data
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}

  app:
    build:
      context: .
    container_name: "steam_profile_app"
    hostname: "steam_profile"
    depends_on:
      - postgresql
    ports:
      - "8000:${APP_PORT}"
    volumes:
      - .:/steam_profile_app/api
      - ./static:/steam_profile_app/api/static
      - ./templates:/steam_profile_app/api/templates
    env_file:
      - .env.prod
    environment:
      MODE: "PROD"

  nginx:
    image: nginx:latest
    container_name: "steam_profile_nginx"
    build:
      context: ./nginx
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    env_file:
      - .env.prod
    depends_on:
      - app
    volumes:
      - ./nginx/templates:/etc/nginx/templates

volumes:
  steam_profile_postgresql_data: